server:
  port: 8080

spring:
  config:
    name: floristic-boom

  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  data:
    web:
      pageable:
        default-page-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      mysql:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: true
        show_sql: true

logging:
  level:
    root: debug